#include <mpmc/ad/math.hpp>

#include <array>
#include <cmath>
#include <concepts>
#include <cstddef>
#include <exception>
#include <iomanip>
#include <initializer_list>
#include <iostream>
#include <limits>
#include <numbers>
#include <source_location>
#include <stdexcept>
#include <string>
#include <string_view>
#include <type_traits>

mpmc::ad::Dual<double, 2> evaluate_math_in_other_translation_unit();

namespace {

namespace ad = mpmc::ad;

template <typename L, typename R>
concept Powerable = requires(L lhs, R rhs) { ad::pow(lhs, rhs); };

using D = ad::Dual<double, 3>;
static_assert(std::same_as<decltype(ad::log(D{})), D>);
static_assert(std::same_as<decltype(ad::pow(ad::Dual<float>{}, 1.5)), ad::Dual<float>>);
static_assert(!Powerable<D, ad::Dual<double, 2>>);
static_assert(!Powerable<D, ad::Dual<float, 3>>);
static_assert(!Powerable<D, bool> && !Powerable<D, unsigned int>);
static_assert(!noexcept(ad::sqrt(D{})));

// Runtime checks stay active in Release; no NDEBUG-sensitive assertions.
void require(bool condition, std::string_view message,
             const std::source_location location = std::source_location::current()) {
    if (!condition) {
        throw std::runtime_error(std::string(location.file_name()) + ":" +
                                 std::to_string(location.line()) + ": " + std::string(message));
    }
}

template <std::floating_point T>
void near(T actual, T expected, T absolute_tolerance = T{64} * std::numeric_limits<T>::epsilon(),
          const std::source_location location = std::source_location::current()) {
    // Analytic, dimensionless short expressions. A zero absolute tolerance is
    // mandatory for small nonzero reference derivatives; zero must not pass.
    const T relative_tolerance = T{64} * std::numeric_limits<T>::epsilon();
    const bool matches = std::isfinite(actual) && std::isfinite(expected) &&
                         std::abs(actual - expected) <=
                             absolute_tolerance + relative_tolerance * std::abs(expected);
    if (!matches) {
        std::cerr << std::setprecision(std::numeric_limits<T>::max_digits10)
                  << "actual=" << actual << ", expected=" << expected << '\n';
    }
    require(matches, "value/derivative outside tolerance", location);
}

template <typename Callable>
void domain_error(Callable callable,
                  const std::source_location location = std::source_location::current()) {
    try {
        callable();
    } catch (const std::domain_error&) {
        return;
    }
    require(false, "expected std::domain_error was not thrown", location);
}

template <std::floating_point T, std::size_t N>
void check(const ad::Dual<T, N>& actual, T value, const std::array<T, N>& gradient) {
    near(actual.value(), value);
    for (std::size_t i = 0; i < N; ++i) {
        near(actual.derivative(i), gradient[i]);
    }
}

template <std::floating_point T>
struct Point {
    T x;
    T value;
    T slope;
};

template <std::floating_point T>
struct UnaryCase {
    std::string_view name;
    ad::Dual<T, 3> (*function)(const ad::Dual<T, 3>&);
    std::array<Point<T>, 3> points;
    std::array<T, 4> invalid;
    std::size_t invalid_count;
};

// Values/slopes are hand-derived at special points, not generated by the AD
// implementation or by finite differences. pi and logarithmic constants are
// rounded to the scalar type under test. Each entry is its own CTest test.
template <std::floating_point T>
std::array<UnaryCase<T>, 22> unary_cases() {
    const T pi = std::numbers::pi_v<T>;
    const T l2 = std::numbers::ln2_v<T>;
    const T l10 = std::numbers::ln10_v<T>;
    const T s3 = std::numbers::sqrt3_v<T>;
    const T half = T{1} / T{2};
    const T three_fifths = T{3} / T{5};
    const std::array<T, 4> positive_only{T{0}, -T{0}, T{-1}, T{-2}};
    const std::array<T, 4> open_unit{T{-1}, T{1}, T{-2}, T{2}};
    return {{
        {"exp", &ad::exp<T, 3>, {{{T{0}, T{1}, T{1}}, {l2, T{2}, T{2}},
                                  {-l2, half, half}}}, {}, 0},
        {"exp2", &ad::exp2<T, 3>, {{{T{0}, T{1}, l2}, {T{1}, T{2}, T{2} * l2},
                                    {T{-1}, half, half * l2}}}, {}, 0},
        {"expm1", &ad::expm1<T, 3>, {{{T{0}, T{0}, T{1}}, {l2, T{1}, T{2}},
                                      {-l2, -half, half}}}, {}, 0},
        {"log", &ad::log<T, 3>, {{{T{1}, T{0}, T{1}}, {T{2}, l2, half},
                                  {half, -l2, T{2}}}}, positive_only, 4},
        {"log2", &ad::log2<T, 3>, {{{T{1}, T{0}, T{1} / l2}, {T{2}, T{1}, half / l2},
                                    {half, T{-1}, T{2} / l2}}}, positive_only, 4},
        {"log10", &ad::log10<T, 3>, {{{T{1}, T{0}, T{1} / l10},
                                      {T{10}, T{1}, T{1} / (T{10} * l10)},
                                      {T{1} / T{10}, T{-1}, T{10} / l10}}}, positive_only, 4},
        {"log1p", &ad::log1p<T, 3>, {{{T{0}, T{0}, T{1}}, {T{1}, l2, half},
                                      {-half, -l2, T{2}}}}, {T{-1}, T{-2}, T{0}, T{0}}, 2},
        {"sqrt", &ad::sqrt<T, 3>, {{{T{1}, T{1}, half}, {T{4}, T{2}, T{1} / T{4}},
                                    {T{1} / T{4}, half, T{1}}}}, positive_only, 4},
        {"cbrt", &ad::cbrt<T, 3>, {{{T{1}, T{1}, T{1} / T{3}},
                                    {T{8}, T{2}, T{1} / T{12}},
                                    {T{-8}, T{-2}, T{1} / T{12}}}}, {T{0}, -T{0}, T{0}, T{0}}, 2},
        {"sin", &ad::sin<T, 3>, {{{T{0}, T{0}, T{1}}, {pi / T{6}, half, s3 / T{2}},
                                  {-pi / T{6}, -half, s3 / T{2}}}}, {}, 0},
        {"cos", &ad::cos<T, 3>, {{{T{0}, T{1}, T{0}}, {pi / T{3}, half, -s3 / T{2}},
                                  {-pi / T{3}, half, s3 / T{2}}}}, {}, 0},
        {"tan", &ad::tan<T, 3>, {{{T{0}, T{0}, T{1}}, {pi / T{4}, T{1}, T{2}},
                                  {-pi / T{4}, T{-1}, T{2}}}}, {}, 0},
        {"asin", &ad::asin<T, 3>, {{{T{0}, T{0}, T{1}}, {half, pi / T{6}, T{2} / s3},
                                    {-half, -pi / T{6}, T{2} / s3}}}, open_unit, 4},
        {"acos", &ad::acos<T, 3>, {{{T{0}, pi / T{2}, T{-1}}, {half, pi / T{3}, -T{2} / s3},
                                    {-half, T{2} * pi / T{3}, -T{2} / s3}}}, open_unit, 4},
        {"atan", &ad::atan<T, 3>, {{{T{0}, T{0}, T{1}}, {T{1}, pi / T{4}, half},
                                    {T{-1}, -pi / T{4}, half}}}, {}, 0},
        {"sinh", &ad::sinh<T, 3>, {{{T{0}, T{0}, T{1}}, {l2, T{3} / T{4}, T{5} / T{4}},
                                    {-l2, -T{3} / T{4}, T{5} / T{4}}}}, {}, 0},
        {"cosh", &ad::cosh<T, 3>, {{{T{0}, T{1}, T{0}}, {l2, T{5} / T{4}, T{3} / T{4}},
                                    {-l2, T{5} / T{4}, -T{3} / T{4}}}}, {}, 0},
        {"tanh", &ad::tanh<T, 3>, {{{T{0}, T{0}, T{1}}, {l2, three_fifths, T{16} / T{25}},
                                    {-l2, -three_fifths, T{16} / T{25}}}}, {}, 0},
        {"asinh", &ad::asinh<T, 3>, {{{T{0}, T{0}, T{1}}, {T{3} / T{4}, l2, T{4} / T{5}},
                                      {-T{3} / T{4}, -l2, T{4} / T{5}}}}, {}, 0},
        {"acosh", &ad::acosh<T, 3>, {{{T{5} / T{4}, l2, T{4} / T{3}},
                                      {T{17} / T{8}, T{2} * l2, T{8} / T{15}},
                                      {T{65} / T{16}, T{3} * l2, T{16} / T{63}}}},
         {T{1}, T{0}, T{-1}, T{-2}}, 4},
        {"atanh", &ad::atanh<T, 3>, {{{T{0}, T{0}, T{1}},
                                      {three_fifths, l2, T{25} / T{16}},
                                      {-three_fifths, -l2, T{25} / T{16}}}}, open_unit, 4},
        {"abs", &ad::abs<T, 3>, {{{T{1}, T{1}, T{1}}, {T{-2}, T{2}, T{-1}},
                                  {T{3}, T{3}, T{1}}}}, {T{0}, -T{0}, T{0}, T{0}}, 2},
    }};
}

template <std::floating_point T>
bool test_unary(std::string_view name) {
    using Number = ad::Dual<T, 3>;
    for (const auto& test : unary_cases<T>()) {
        if (test.name != name) {
            continue;
        }
        for (const auto& point : test.points) {
            const Number input{point.x, {T{1}, T{-2}, T{0}}};
            check(test.function(input), point.value, {point.slope, T{-2} * point.slope, T{0}});
            check(test.function(Number{point.x}), point.value, {T{0}, T{0}, T{0}});
            check(input, point.x, {T{1}, T{-2}, T{0}}); // The function cannot mutate input.
        }
        for (std::size_t i = 0; i < test.invalid_count; ++i) {
            const Number invalid{test.invalid[i], {T{1}, T{-2}, T{0}}};
            domain_error([&] { (void)test.function(invalid); });
            domain_error([&] { (void)test.function(Number{test.invalid[i]}); });
            check(invalid, test.invalid[i], {T{1}, T{-2}, T{0}});
        }
        // The finite-primal policy is checked for EVERY unary function.
        for (T invalid : {std::numeric_limits<T>::quiet_NaN(),
                          std::numeric_limits<T>::infinity(),
                          -std::numeric_limits<T>::infinity()}) {
            domain_error([&] { (void)test.function(Number{invalid}); });
        }
        return true;
    }
    return false;
}

template <std::floating_point T>
void test_pow_integer() {
    using Number = ad::Dual<T, 3>;
    const Number x{T{-2}, {T{1}, T{-2}, T{0}}};
    constexpr std::array<int, 7> exponents{-3, -2, -1, 0, 1, 2, 3};
    const std::array<T, 7> values{-T{1} / T{8}, T{1} / T{4}, -T{1} / T{2},
                                 T{1}, T{-2}, T{4}, T{-8}};
    const std::array<T, 7> slopes{-T{3} / T{16}, T{1} / T{4}, -T{1} / T{4},
                                 T{0}, T{1}, T{-4}, T{12}};
    for (std::size_t i = 0; i < exponents.size(); ++i) {
        check(ad::pow(x, exponents[i]), values[i], {slopes[i], -T{2} * slopes[i], T{0}});
    }
    const Number zero{T{0}, {T{1}, T{-2}, T{0}}};
    check(ad::pow(zero, 0), T{1}, {T{0}, T{0}, T{0}});
    check(ad::pow(zero, 1), T{0}, {T{1}, T{-2}, T{0}});
    check(ad::pow(zero, 2), T{0}, {T{0}, T{0}, T{0}});
    for (T z : {T{0}, -T{0}}) {
        domain_error([&] { (void)ad::pow(Number{z}, -1); });
    }
    for (int n : {std::numeric_limits<int>::min(), std::numeric_limits<int>::max()}) {
        // Parity must survive exponent conversion, notably for float and INT_MAX.
        const T sign = n % 2 == 0 ? T{1} : T{-1};
        const auto result = ad::pow(Number::variable(T{-1}, 0), n);
        check(result, sign, {-static_cast<T>(n) * sign, T{0}, T{0}});
    }
    for (T invalid : {std::numeric_limits<T>::quiet_NaN(), std::numeric_limits<T>::infinity(),
                      -std::numeric_limits<T>::infinity()}) {
        domain_error([&] { (void)ad::pow(Number{invalid}, 0); });
    }
    check(x, T{-2}, {T{1}, T{-2}, T{0}});
}

template <std::floating_point T>
void test_pow_real() {
    using Number = ad::Dual<T, 3>;
    const Number x{T{4}, {T{1}, T{-2}, T{0}}};
    check(ad::pow(x, T{3} / T{2}), T{8}, {T{3}, T{-6}, T{0}});
    check(ad::pow(x, -T{1} / T{2}), T{1} / T{2}, {-T{1} / T{16}, T{1} / T{8}, T{0}});
    check(ad::pow(x, T{0}), T{1}, {T{0}, T{0}, T{0}});
    check(ad::pow(x, T{1}), T{4}, {T{1}, T{-2}, T{0}});
    if constexpr (std::numeric_limits<long double>::max_exponent >
                  std::numeric_limits<T>::max_exponent) {
        const long double too_large = std::numeric_limits<long double>::max();
        domain_error([&] { (void)ad::pow(x, too_large); });
        domain_error([&] { (void)ad::pow(x, -too_large); });
    }
    // A double literal must not select or convert to the integer-exponent API.
    check(ad::pow(x, 1.5), T{8}, {T{3}, T{-6}, T{0}});
    for (T invalid : {T{0}, -T{0}, T{-1}, std::numeric_limits<T>::quiet_NaN(),
                      std::numeric_limits<T>::infinity(), -std::numeric_limits<T>::infinity()}) {
        domain_error([&] { (void)ad::pow(Number{invalid}, T{2}); });
    }
    for (T invalid : {std::numeric_limits<T>::quiet_NaN(), std::numeric_limits<T>::infinity(),
                      -std::numeric_limits<T>::infinity()}) {
        domain_error([&] { (void)ad::pow(x, invalid); });
    }
    check(x, T{4}, {T{1}, T{-2}, T{0}});
}

template <std::floating_point T>
void test_pow_dual() {
    using Number = ad::Dual<T, 3>;
    const Number x{T{4}, {T{1}, T{0}, T{3}}};
    const Number y{T{1} / T{2}, {T{0}, T{1}, T{-2}}};
    const T l4 = T{2} * std::numbers::ln2_v<T>;
    check(ad::pow(x, y), T{2}, {T{1} / T{4}, T{2} * l4, T{3} / T{4} - T{4} * l4});
    check(ad::pow(x, Number::variable(T{0}, 1)), T{1}, {T{0}, l4, T{0}});
    check(ad::pow(x, Number::variable(T{1}, 1)), T{4}, {T{1}, T{4} * l4, T{3}});
    // y==0 removes the x partial but must not remove the y partial.
    const auto small = ad::pow(Number::variable(std::numeric_limits<T>::min(), 0),
                               Number::variable(T{0}, 1));
    near(small.derivative(0), T{0});
    near(small.derivative(1), std::log(std::numeric_limits<T>::min()));
    for (T invalid : {T{0}, T{-1}, std::numeric_limits<T>::quiet_NaN(),
                      std::numeric_limits<T>::infinity(), -std::numeric_limits<T>::infinity()}) {
        domain_error([&] { (void)ad::pow(Number{invalid}, Number{T{2}}); });
    }
    for (T invalid : {std::numeric_limits<T>::quiet_NaN(), std::numeric_limits<T>::infinity(),
                      -std::numeric_limits<T>::infinity()}) {
        domain_error([&] { (void)ad::pow(x, Number{invalid}); });
    }
    check(x, T{4}, {T{1}, T{0}, T{3}});
    check(y, T{1} / T{2}, {T{0}, T{1}, T{-2}});
}

template <std::floating_point T>
void test_pow_scalar_base() {
    using Number = ad::Dual<T, 3>;
    const Number y{T{3}, {T{1}, T{-2}, T{0}}};
    const T slope = T{8} * std::numbers::ln2_v<T>;
    check(ad::pow(T{2}, y), T{8}, {slope, -T{2} * slope, T{0}});
    check(ad::pow(T{1}, y), T{1}, {T{0}, T{0}, T{0}});
    for (T invalid : {T{0}, T{-1}, std::numeric_limits<T>::quiet_NaN(),
                      std::numeric_limits<T>::infinity(), -std::numeric_limits<T>::infinity()}) {
        domain_error([&] { (void)ad::pow(invalid, y); });
    }
    for (T invalid : {std::numeric_limits<T>::quiet_NaN(), std::numeric_limits<T>::infinity(),
                      -std::numeric_limits<T>::infinity()}) {
        domain_error([&] { (void)ad::pow(T{2}, Number{invalid}); });
    }
    check(y, T{3}, {T{1}, T{-2}, T{0}});
}

// Import scalar overloads locally; argument-dependent lookup selects AD
// overloads without extracting value() or changing the expression's type.
template <typename Number>
Number composed_function(const Number& x, const Number& y) {
    using std::exp;
    using std::log;
    using std::sin;
    using std::sqrt;
    return exp(x * y) + log(x) + sqrt(y) + sin(x);
}

template <std::floating_point T>
void test_composition() {
    using Number = ad::Dual<T, 2>;
    for (T a : {T{1} / T{2}, T{1}, T{2}}) {
        for (T b : {T{1} / T{4}, T{1}, T{2}}) {
            const T exponential = std::exp(a * b);
            // Differentiated by hand, independently of the generic expression.
            const T dx = b * exponential + T{1} / a + std::cos(a);
            const T dy = a * exponential + T{1} / (T{2} * std::sqrt(b));
            const auto result = composed_function(Number::variable(a, 0), Number::variable(b, 1));
            check(result, composed_function(a, b), {dx, dy});
            const auto jvp = composed_function(ad::Dual<T>{a, {T{3}}}, ad::Dual<T>{b, {T{-2}}});
            near(jvp.derivative(0), T{3} * dx - T{2} * dy);
        }
    }
}

template <std::floating_point T>
void test_range_regressions() {
    using Number = ad::Dual<T>;
    const T tiny = std::numeric_limits<T>::epsilon() / T{16};
    // At this scale, log1p(x) and expm1(x) round to x, not to zero.
    near(ad::log1p(Number::variable(tiny, 0)).value(), tiny, T{0});
    near(ad::expm1(Number::variable(tiny, 0)).value(), tiny, T{0});
    near(ad::expm1(Number::variable(T{-40}, 0)).derivative(0), std::exp(T{-40}), T{0});
    for (T a : {T{-20}, T{20}}) {
        const T expected = T{1} / (std::cosh(a) * std::cosh(a));
        near(ad::tanh(Number::variable(a, 0)).derivative(0), expected, T{0});
    }
    const T large = std::numeric_limits<T>::max() / T{4};
    near(ad::asinh(Number{large, {large}}).derivative(0), T{1});
    near(ad::acosh(Number{large, {large}}).derivative(0), T{1});
    near(ad::log10(Number{large, {large}}).derivative(0), T{1} / std::numbers::ln10_v<T>);
    const T small = std::numeric_limits<T>::min();
    near(ad::log(Number{small, {small}}).derivative(0), T{1});
    // Adjacent representable points stay admissible; endpoints do not.
    const T edge = std::nextafter(T{1}, T{0});
    const auto asin_edge = ad::asin(Number::variable(edge, 0));
    const auto acos_edge = ad::acos(Number::variable(edge, 0));
    near(asin_edge.derivative(0), -acos_edge.derivative(0), T{0});
    require(asin_edge.derivative(0) > T{1}, "near-boundary derivative must not be clipped");
    const T almost_pole = std::nextafter(std::numbers::pi_v<T> / T{2}, T{0});
    const auto tan_edge = ad::tan(Number::variable(almost_pole, 0));
    require(std::isfinite(tan_edge.value()) && tan_edge.derivative(0) > T{1},
            "rounded near-pole arguments must not be rejected using epsilon");
}

void test_double_scale_regressions() {
    using Number = ad::Dual<double>;
    near(ad::atan(Number{1e200, {1e200}}).derivative(0), 1e-200, 0.0);
    near(ad::pow(Number{1e200, {1e200}}, -1).derivative(0), -1e-200, 0.0);
    near(ad::pow(Number::variable(1e-200, 0), 2).derivative(0), 2e-200, 0.0);
    const double exponential = std::exp(400.0);
    near(ad::tanh(Number{400.0, {exponential}}).derivative(0), 4.0 / exponential, 0.0);
    if constexpr (std::numeric_limits<double>::has_denorm == std::denorm_present) {
        const double subnormal = std::numeric_limits<double>::denorm_min();
        near(ad::log(Number{subnormal, {subnormal}}).derivative(0), 1.0);
    }
}

template <std::floating_point T>
void test_overflow_policy() {
    using Number = ad::Dual<T>;
    if constexpr (std::numeric_limits<T>::is_iec559) {
        const T a = std::log(std::numeric_limits<T>::max()) + T{4};
        const auto overflow = ad::exp(Number::variable(a, 0));
        require(std::isinf(overflow.value()) && std::isinf(overflow.derivative(0)),
                "range overflow must not be clipped or disguised");
        const T underflow_input = -T{2} * std::log(std::numeric_limits<T>::max());
        const auto underflow = ad::exp(Number::variable(underflow_input, 0));
        require(underflow.value() == T{0} && underflow.derivative(0) == T{0},
                "underflow follows the underlying floating-point range");
        const auto invalid_seed = ad::sin(Number{T{0}, {std::numeric_limits<T>::quiet_NaN()}});
        require(std::isnan(invalid_seed.derivative(0)), "invalid seeds must not be sanitized");
    }
}

template <std::floating_point T>
void run_case(std::string_view name) {
    if (test_unary<T>(name)) {
        return;
    }
    if (name == "pow_integer") {
        test_pow_integer<T>();
    } else if (name == "pow_real") {
        test_pow_real<T>();
    } else if (name == "pow_dual") {
        test_pow_dual<T>();
    } else if (name == "pow_scalar_base") {
        test_pow_scalar_base<T>();
    } else if (name == "composition") {
        test_composition<T>();
    } else if (name == "range_regressions") {
        test_range_regressions<T>();
    } else if (name == "overflow_policy") {
        test_overflow_policy<T>();
    } else {
        throw std::runtime_error("unknown test case: " + std::string(name));
    }
}

} // namespace

int main(int argc, char** argv) {
    try {
        require(argc == 2, "pass exactly one named math test case");
        const std::string_view name{argv[1]};
        if (name == "header_odr") {
            check(evaluate_math_in_other_translation_unit(), 7.0, {1.0, 1.0 / 6.0});
        } else {
            run_case<float>(name);
            run_case<double>(name);
            run_case<long double>(name);
            if (name == "range_regressions") {
                test_double_scale_regressions();
            }
        }
        std::cout << "[PASS] " << name << '\n';
        return 0;
    } catch (const std::exception& error) {
        std::cerr << "[FAIL] " << error.what() << '\n';
        return 1;
    }
}
