cmake_minimum_required(VERSION 3.21)
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
    project(mpmc_flash_sensitivity LANGUAGES CXX)
endif()
if(NOT TARGET mpmc::flash)
    add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/.." flash-library)
endif()
if(NOT TARGET mpmc::ad)
    add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/../../ad" ad-library)
endif()
add_library(mpmc_flash_sensitivity INTERFACE)
add_library(mpmc::flash_sensitivity ALIAS mpmc_flash_sensitivity)
target_compile_features(mpmc_flash_sensitivity INTERFACE cxx_std_20)
target_link_libraries(mpmc_flash_sensitivity INTERFACE mpmc::flash mpmc::ad)
