#ifndef MPMC_THERMODYNAMICS_CPA_PARAMETERS_HPP
#define MPMC_THERMODYNAMICS_CPA_PARAMETERS_HPP

#include <mpmc/thermodynamics/components.hpp>

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <limits>
#include <map>
#include <set>
#include <span>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace mpmc::thermodynamics {

inline constexpr std::string_view cpa_profile =
    "CPA/SRK-physical/simplified-rdf-1.9eta/explicit-site-pairs/v1";

// CPA parameters are not represented with the generic Unit enum because the
// repository currently has no units for a0 or association energy. Each field
// has a fixed SI unit in its name and retains full provenance explicitly.
struct CpaSourcedValue {
    double value{};
    Provenance source;
};

struct CpaAssociationSiteInput {
    std::string id;
    std::size_t multiplicity{1U};
};

struct CpaPureParameterInput {
    std::string component_id;
    CpaSourcedValue critical_temperature_k;
    CpaSourcedValue a0_pa_m6_per_mol2;
    CpaSourcedValue b_m3_per_mol;
    CpaSourcedValue c1_dimensionless;
    std::vector<CpaAssociationSiteInput> sites;
};

struct CpaBinaryInteractionInput {
    std::string first_component_id;
    std::string second_component_id;
    CpaSourcedValue kij_dimensionless;
};

// Absence of a site-pair record means that association between those site
// classes is disabled by this configured profile. Cross-association is never
// generated by a hidden combining rule.
struct CpaAssociationPairInput {
    std::string first_component_id;
    std::string first_site_id;
    std::string second_component_id;
    std::string second_site_id;
    CpaSourcedValue epsilon_j_per_mol;
    CpaSourcedValue beta_dimensionless;
};

struct CpaParameterInput {
    std::string model_id{std::string(cpa_profile)};
    std::string dataset_id;
    std::string revision;
    Applicability applicability;
    std::vector<CpaPureParameterInput> pure;
    std::vector<CpaBinaryInteractionInput> binary;
    std::vector<CpaAssociationPairInput> association_pairs;
};

// Compact numerical payload used by inner thermodynamic kernels. The owning
// CpaParameterSet separately retains sourced records for audit/provenance.
struct CpaPureParameters {
    double critical_temperature_k{};
    double a0_pa_m6_per_mol2{};
    double b_m3_per_mol{};
    double c1_dimensionless{};
    std::vector<CpaAssociationSiteInput> sites;
};

struct CpaAssociationPairParameters {
    double epsilon_j_per_mol{};
    double beta_dimensionless{};
};

namespace cpa_detail {

inline void require_cpa(bool condition, ContractErrorCode code,
                        const std::string& field, std::string_view reason) {
    if (!condition) { throw ContractError(code, field, reason); }
}

inline void validate_value(const CpaSourcedValue& value,
                           const std::string& field,
                           DataPolicy policy,
                           bool positive,
                           bool nonnegative = false) {
    const bool domain = std::isfinite(value.value) &&
        (!positive || value.value > 0.0) &&
        (!nonnegative || value.value >= 0.0);
    require_cpa(domain, ContractErrorCode::invalid_value, field,
                positive ? "expected finite positive SI value"
                         : (nonnegative ? "expected finite nonnegative value"
                                        : "expected finite value"));
    detail::validate_source(value.source, field + ".source", policy);
}

inline std::pair<std::string, std::string> ordered_component_pair(
    std::string first, std::string second) {
    if (second < first) { std::swap(first, second); }
    return {std::move(first), std::move(second)};
}

using SiteKey = std::pair<std::string, std::string>;
using AssociationKey = std::pair<SiteKey, SiteKey>;

inline AssociationKey ordered_association_pair(
    SiteKey first, SiteKey second) {
    if (second < first) { std::swap(first, second); }
    return {std::move(first), std::move(second)};
}

} // namespace cpa_detail

class CpaParameterSet {
public:
    CpaParameterSet(const CpaParameterSet&) = default;
    CpaParameterSet(CpaParameterSet&&) noexcept = default;
    CpaParameterSet& operator=(const CpaParameterSet&) = delete;
    CpaParameterSet& operator=(CpaParameterSet&&) = delete;

    [[nodiscard]] static CpaParameterSet create(
        std::span<const Component> catalog,
        std::span<const std::string> order,
        const CpaParameterInput& input,
        DataPolicy policy = DataPolicy::ordinary,
        ContractLimits limits = {}) {
        using namespace cpa_detail;
        require_cpa(input.model_id == cpa_profile,
                    ContractErrorCode::unsupported_model, "cpa.model_id",
                    "unsupported CPA profile");
        detail::require_text(input.dataset_id, "cpa.dataset_id");
        detail::require_text(input.revision, "cpa.revision");
        input.applicability.validate(policy);
        require_cpa(input.pure.size() <= limits.max_components &&
                        input.binary.size() <= limits.max_pair_records &&
                        input.association_pairs.size() <= limits.max_pair_records,
                    ContractErrorCode::size_limit, "cpa.parameters",
                    "parameter-record quota exceeded");

        CpaParameterSet result(
            OrderedComponents::select(catalog, order, policy, limits));
        result.dataset_id_ = input.dataset_id;
        result.revision_ = input.revision;
        result.applicability_ = input.applicability;

        const std::size_t n = result.components_.size();
        require_cpa(n == 0U || n - 1U <=
                        std::numeric_limits<std::size_t>::max() / n,
                    ContractErrorCode::size_limit, "cpa.parameters",
                    "selected pair count overflows size_t");
        const std::size_t selected_pair_count =
            n < 2U ? 0U : n * (n - 1U) / 2U;
        require_cpa(selected_pair_count <= limits.max_pair_records &&
                        selected_pair_count <=
                            std::vector<CpaBinaryInteractionInput>{}.max_size(),
                    ContractErrorCode::size_limit, "cpa.parameters",
                    "selected pair count exceeds resource limits");

        std::set<std::string, std::less<>> catalog_ids;
        for (const auto& component : catalog) { catalog_ids.insert(component.id); }

        std::map<std::string, const CpaPureParameterInput*, std::less<>> pure_by_id;
        for (const auto& pure : input.pure) {
            detail::validate_id(pure.component_id, "cpa.pure.component_id");
            require_cpa(catalog_ids.contains(pure.component_id),
                        ContractErrorCode::unknown_component,
                        "cpa.pure[" + pure.component_id + "]",
                        "pure record references component outside catalog");
            require_cpa(pure_by_id.emplace(pure.component_id, &pure).second,
                        ContractErrorCode::duplicate_parameter,
                        "cpa.pure[" + pure.component_id + "]",
                        "duplicate pure-component CPA record");

            validate_value(pure.critical_temperature_k,
                           "cpa.pure[" + pure.component_id + "].critical_temperature_k",
                           policy, true);
            validate_value(pure.a0_pa_m6_per_mol2,
                           "cpa.pure[" + pure.component_id + "].a0_pa_m6_per_mol2",
                           policy, true);
            validate_value(pure.b_m3_per_mol,
                           "cpa.pure[" + pure.component_id + "].b_m3_per_mol",
                           policy, true);
            validate_value(pure.c1_dimensionless,
                           "cpa.pure[" + pure.component_id + "].c1_dimensionless",
                           policy, false);

            std::set<std::string, std::less<>> site_ids;
            for (const auto& site : pure.sites) {
                detail::validate_id(
                    site.id, "cpa.pure[" + pure.component_id + "].site.id");
                require_cpa(site.multiplicity > 0U,
                            ContractErrorCode::invalid_value,
                            "cpa.pure[" + pure.component_id + "].site[" + site.id + "]",
                            "site multiplicity must be positive");
                require_cpa(site_ids.insert(site.id).second,
                            ContractErrorCode::duplicate_identifier,
                            "cpa.pure[" + pure.component_id + "].site[" + site.id + "]",
                            "duplicate association site class");
            }
        }

        result.pure_.reserve(result.components_.size());
        result.pure_records_.reserve(result.components_.size());
        for (const auto& component : result.components_.items()) {
            const auto found = pure_by_id.find(component.id);
            require_cpa(found != pure_by_id.end(), ContractErrorCode::missing_parameter,
                        "cpa.pure[" + component.id + "]",
                        "missing CPA pure-component parameters");
            const auto& pure = *found->second;
            result.pure_records_.push_back(pure);
            result.pure_.push_back({
                pure.critical_temperature_k.value,
                pure.a0_pa_m6_per_mol2.value,
                pure.b_m3_per_mol.value,
                pure.c1_dimensionless.value,
                pure.sites});
        }

        using ComponentPair = std::pair<std::string, std::string>;
        std::map<ComponentPair, const CpaBinaryInteractionInput*> binary_by_pair;
        for (const auto& binary : input.binary) {
            detail::validate_id(binary.first_component_id, "cpa.binary.first");
            detail::validate_id(binary.second_component_id, "cpa.binary.second");
            require_cpa(catalog_ids.contains(binary.first_component_id) &&
                            catalog_ids.contains(binary.second_component_id),
                        ContractErrorCode::unknown_component, "cpa.binary",
                        "binary interaction references component outside catalog");
            require_cpa(binary.first_component_id != binary.second_component_id,
                        ContractErrorCode::invalid_pair, "cpa.binary",
                        "binary interaction requires two distinct components");
            validate_value(binary.kij_dimensionless, "cpa.binary.kij",
                           policy, false);
            const auto key = ordered_component_pair(
                binary.first_component_id, binary.second_component_id);
            require_cpa(binary_by_pair.emplace(key, &binary).second,
                        ContractErrorCode::duplicate_parameter, "cpa.binary",
                        "duplicate unordered binary interaction");
        }

        result.binary_records_.reserve(selected_pair_count);
        for (std::size_t i = 0; i < n; ++i) {
            for (std::size_t j = i + 1U; j < n; ++j) {
                const auto key = ordered_component_pair(
                    result.components_.at(i).id, result.components_.at(j).id);
                const auto found = binary_by_pair.find(key);
                require_cpa(found != binary_by_pair.end(),
                            ContractErrorCode::missing_parameter, "cpa.binary",
                            "explicit kij required for every selected component pair");
                auto record = *found->second;
                record.first_component_id = result.components_.at(i).id;
                record.second_component_id = result.components_.at(j).id;
                result.kij_.emplace(key, record.kij_dimensionless.value);
                result.binary_records_.push_back(std::move(record));
            }
        }

        const auto catalog_site_exists = [&](const std::string& component_id,
                                             const std::string& site_id) {
            const auto found = pure_by_id.find(component_id);
            if (found == pure_by_id.end()) { return false; }
            return std::any_of(
                found->second->sites.begin(), found->second->sites.end(),
                [&](const CpaAssociationSiteInput& site) {
                    return site.id == site_id;
                });
        };

        std::set<AssociationKey> association_keys;
        for (const auto& pair : input.association_pairs) {
            detail::validate_id(pair.first_component_id, "cpa.association.first_component");
            detail::validate_id(pair.second_component_id, "cpa.association.second_component");
            detail::validate_id(pair.first_site_id, "cpa.association.first_site");
            detail::validate_id(pair.second_site_id, "cpa.association.second_site");
            require_cpa(catalog_ids.contains(pair.first_component_id) &&
                            catalog_ids.contains(pair.second_component_id),
                        ContractErrorCode::unknown_component, "cpa.association",
                        "association pair references component outside catalog");
            require_cpa(catalog_site_exists(pair.first_component_id, pair.first_site_id) &&
                            catalog_site_exists(pair.second_component_id, pair.second_site_id),
                        ContractErrorCode::invalid_pair, "cpa.association",
                        "association pair references undeclared site class");
            validate_value(pair.epsilon_j_per_mol, "cpa.association.epsilon_j_per_mol",
                           policy, true);
            validate_value(pair.beta_dimensionless, "cpa.association.beta_dimensionless",
                           policy, false, true);
            const auto key = ordered_association_pair(
                {pair.first_component_id, pair.first_site_id},
                {pair.second_component_id, pair.second_site_id});
            require_cpa(association_keys.insert(key).second,
                        ContractErrorCode::duplicate_parameter, "cpa.association",
                        "duplicate unordered association site-pair interaction");

            if (!result.components_.contains(pair.first_component_id) ||
                !result.components_.contains(pair.second_component_id)) {
                continue;
            }
            result.association_.emplace(
                key, CpaAssociationPairParameters{
                    pair.epsilon_j_per_mol.value,
                    pair.beta_dimensionless.value});
            result.association_records_.push_back(pair);
        }
        return result;
    }

    [[nodiscard]] static constexpr std::string_view model_id() noexcept {
        return cpa_profile;
    }
    [[nodiscard]] std::size_t size() const noexcept { return components_.size(); }
    [[nodiscard]] const OrderedComponents& components() const & noexcept { return components_; }
    const OrderedComponents& components() const && = delete;
    [[nodiscard]] const CpaPureParameters& pure(std::size_t index) const & {
        return pure_.at(index);
    }
    const CpaPureParameters& pure(std::size_t) const && = delete;
    [[nodiscard]] std::span<const CpaPureParameterInput> pure_records() const & noexcept {
        return pure_records_;
    }
    std::span<const CpaPureParameterInput> pure_records() const && = delete;
    [[nodiscard]] std::span<const CpaBinaryInteractionInput> binary_records() const & noexcept {
        return binary_records_;
    }
    std::span<const CpaBinaryInteractionInput> binary_records() const && = delete;
    [[nodiscard]] std::span<const CpaAssociationPairInput> association_records() const & noexcept {
        return association_records_;
    }
    std::span<const CpaAssociationPairInput> association_records() const && = delete;

    [[nodiscard]] double kij(std::size_t first, std::size_t second) const {
        if (first >= components_.size() || second >= components_.size()) {
            throw std::out_of_range("CpaParameterSet::kij: index outside component order");
        }
        if (first == second) { return 0.0; }
        const auto key = cpa_detail::ordered_component_pair(
            components_.at(first).id, components_.at(second).id);
        const auto found = kij_.find(key);
        if (found == kij_.end()) {
            throw ContractError(ContractErrorCode::missing_parameter,
                                "cpa.binary", "missing explicit kij");
        }
        return found->second;
    }

    [[nodiscard]] const CpaAssociationPairParameters* association_pair(
        std::size_t first_component, std::string_view first_site,
        std::size_t second_component, std::string_view second_site) const {
        if (first_component >= components_.size() || second_component >= components_.size()) {
            return nullptr;
        }
        const auto key = cpa_detail::ordered_association_pair(
            {components_.at(first_component).id, std::string(first_site)},
            {components_.at(second_component).id, std::string(second_site)});
        const auto found = association_.find(key);
        return found == association_.end() ? nullptr : &found->second;
    }

    [[nodiscard]] const std::string& dataset_id() const & noexcept { return dataset_id_; }
    const std::string& dataset_id() const && = delete;
    [[nodiscard]] const std::string& revision() const & noexcept { return revision_; }
    const std::string& revision() const && = delete;
    [[nodiscard]] const Applicability& applicability() const & noexcept { return applicability_; }
    const Applicability& applicability() const && = delete;

private:
    explicit CpaParameterSet(OrderedComponents components)
        : components_(std::move(components)) {}

    OrderedComponents components_;
    std::vector<CpaPureParameters> pure_;
    std::vector<CpaPureParameterInput> pure_records_;
    std::vector<CpaBinaryInteractionInput> binary_records_;
    std::vector<CpaAssociationPairInput> association_records_;
    std::map<std::pair<std::string, std::string>, double> kij_;
    std::map<cpa_detail::AssociationKey, CpaAssociationPairParameters> association_;
    std::string dataset_id_;
    std::string revision_;
    Applicability applicability_;
};

} // namespace mpmc::thermodynamics

#endif // MPMC_THERMODYNAMICS_CPA_PARAMETERS_HPP
