#ifndef MPMC_THERMODYNAMICS_CPA_PARAMETERS_HPP
#define MPMC_THERMODYNAMICS_CPA_PARAMETERS_HPP

#include <mpmc/thermodynamics/components.hpp>

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <map>
#include <span>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace mpmc::thermodynamics {

inline constexpr std::string_view cpa_profile =
    "CPA/SRK-physical/simplified-rdf-1999/explicit-site-pairs/v1";

struct CpaSourcedValue {
    double value{};
    Provenance source;
};

struct CpaAssociationSiteInput {
    std::string id;
    std::size_t multiplicity{1U};
};

struct CpaPureParameterInput {
    std::string component_id;
    CpaSourcedValue critical_temperature_k;
    CpaSourcedValue a0_pa_m6_per_mol2;
    CpaSourcedValue b_m3_per_mol;
    CpaSourcedValue c1_dimensionless;
    std::vector<CpaAssociationSiteInput> sites;
};

struct CpaBinaryInteractionInput {
    std::string first_component_id;
    std::string second_component_id;
    CpaSourcedValue kij_dimensionless;
};

// Absence of a site-pair record means that association between those site classes
// is prohibited by the configured association scheme. Cross-association is never
// generated by a hidden combining rule in this profile.
struct CpaAssociationPairInput {
    std::string first_component_id;
    std::string first_site_id;
    std::string second_component_id;
    std::string second_site_id;
    CpaSourcedValue epsilon_j_per_mol;
    CpaSourcedValue beta_dimensionless;
};

struct CpaParameterInput {
    std::string model_id{std::string(cpa_profile)};
    std::string dataset_id;
    std::string revision;
    Applicability applicability;
    std::vector<CpaPureParameterInput> pure;
    std::vector<CpaBinaryInteractionInput> binary;
    std::vector<CpaAssociationPairInput> association_pairs;
};

struct CpaPureParameters {
    double critical_temperature_k{};
    double a0_pa_m6_per_mol2{};
    double b_m3_per_mol{};
    double c1_dimensionless{};
    std::vector<CpaAssociationSiteInput> sites;
};

struct CpaAssociationPairParameters {
    double epsilon_j_per_mol{};
    double beta_dimensionless{};
};

namespace cpa_detail {

inline void require_cpa(bool condition, ContractErrorCode code,
                        const std::string& field, std::string_view reason) {
    if (!condition) { throw ContractError(code, field, reason); }
}

inline void validate_value(const CpaSourcedValue& value,
                           const std::string& field,
                           DataPolicy policy,
                           bool positive,
                           bool nonnegative = false) {
    const bool domain = std::isfinite(value.value) &&
        (!positive || value.value > 0.0) &&
        (!nonnegative || value.value >= 0.0);
    require_cpa(domain, ContractErrorCode::invalid_value, field,
                positive ? "expected finite positive SI value"
                         : (nonnegative ? "expected finite nonnegative value"
                                        : "expected finite value"));
    detail::validate_source(value.source, field + ".source", policy);
}

inline std::pair<std::string, std::string> ordered_component_pair(
    std::string first, std::string second) {
    if (second < first) { std::swap(first, second); }
    return {std::move(first), std::move(second)};
}

using SiteKey = std::pair<std::string, std::string>;
using AssociationKey = std::pair<SiteKey, SiteKey>;

inline AssociationKey ordered_association_pair(
    SiteKey first, SiteKey second) {
    if (second < first) { std::swap(first, second); }
    return {std::move(first), std::move(second)};
}

} // namespace cpa_detail

class CpaParameterSet {
public:
    CpaParameterSet(const CpaParameterSet&) = default;
    CpaParameterSet(CpaParameterSet&&) noexcept = default;
    CpaParameterSet& operator=(const CpaParameterSet&) = delete;
    CpaParameterSet& operator=(CpaParameterSet&&) = delete;

    [[nodiscard]] static CpaParameterSet create(
        std::span<const Component> catalog,
        std::span<const std::string> order,
        const CpaParameterInput& input,
        DataPolicy policy = DataPolicy::ordinary,
        ContractLimits limits = {}) {
        using namespace cpa_detail;
        require_cpa(input.model_id == cpa_profile,
                    ContractErrorCode::unsupported_model, "cpa.model_id",
                    "unsupported CPA profile");
        detail::require_text(input.dataset_id, "cpa.dataset_id");
        detail::require_text(input.revision, "cpa.revision");
        input.applicability.validate(policy);

        CpaParameterSet result(
            OrderedComponents::select(catalog, order, policy, limits));
        result.dataset_id_ = input.dataset_id;
        result.revision_ = input.revision;
        result.applicability_ = input.applicability;

        std::map<std::string, const CpaPureParameterInput*, std::less<>> pure_by_id;
        for (const auto& pure : input.pure) {
            detail::validate_id(pure.component_id, "cpa.pure.component_id");
            require_cpa(pure_by_id.emplace(pure.component_id, &pure).second,
                        ContractErrorCode::duplicate_parameter,
                        "cpa.pure[" + pure.component_id + "]",
                        "duplicate pure-component CPA record");
        }

        result.pure_.reserve(result.components_.size());
        for (const auto& component : result.components_.items()) {
            const auto found = pure_by_id.find(component.id);
            require_cpa(found != pure_by_id.end(), ContractErrorCode::missing_parameter,
                        "cpa.pure[" + component.id + "]",
                        "missing CPA pure-component parameters");
            const auto& pure = *found->second;
            validate_value(pure.critical_temperature_k,
                           "cpa.pure[" + component.id + "].critical_temperature_k",
                           policy, true);
            validate_value(pure.a0_pa_m6_per_mol2,
                           "cpa.pure[" + component.id + "].a0_pa_m6_per_mol2",
                           policy, true);
            validate_value(pure.b_m3_per_mol,
                           "cpa.pure[" + component.id + "].b_m3_per_mol",
                           policy, true);
            validate_value(pure.c1_dimensionless,
                           "cpa.pure[" + component.id + "].c1_dimensionless",
                           policy, false);

            std::map<std::string, std::size_t, std::less<>> site_ids;
            for (const auto& site : pure.sites) {
                detail::validate_id(site.id,
                    "cpa.pure[" + component.id + "].site.id");
                require_cpa(site.multiplicity > 0U,
                            ContractErrorCode::invalid_value,
                            "cpa.pure[" + component.id + "].site[" + site.id + "]",
                            "site multiplicity must be positive");
                require_cpa(site_ids.emplace(site.id, site.multiplicity).second,
                            ContractErrorCode::duplicate_identifier,
                            "cpa.pure[" + component.id + "].site[" + site.id + "]",
                            "duplicate association site class");
            }
            result.pure_.push_back({
                pure.critical_temperature_k.value,
                pure.a0_pa_m6_per_mol2.value,
                pure.b_m3_per_mol.value,
                pure.c1_dimensionless.value,
                pure.sites});
        }

        for (const auto& binary : input.binary) {
            detail::validate_id(binary.first_component_id, "cpa.binary.first");
            detail::validate_id(binary.second_component_id, "cpa.binary.second");
            require_cpa(binary.first_component_id != binary.second_component_id,
                        ContractErrorCode::invalid_pair, "cpa.binary",
                        "binary interaction requires two distinct components");
            require_cpa(result.components_.contains(binary.first_component_id) &&
                            result.components_.contains(binary.second_component_id),
                        ContractErrorCode::unknown_component, "cpa.binary",
                        "binary interaction references component outside ordered snapshot");
            validate_value(binary.kij_dimensionless, "cpa.binary.kij",
                           policy, false);
            const auto key = ordered_component_pair(
                binary.first_component_id, binary.second_component_id);
            require_cpa(result.kij_.emplace(key, binary.kij_dimensionless.value).second,
                        ContractErrorCode::duplicate_parameter, "cpa.binary",
                        "duplicate binary interaction");
        }

        for (std::size_t i = 0; i < result.components_.size(); ++i) {
            for (std::size_t j = i + 1U; j < result.components_.size(); ++j) {
                const auto key = ordered_component_pair(
                    result.components_.at(i).id, result.components_.at(j).id);
                require_cpa(result.kij_.contains(key),
                            ContractErrorCode::missing_parameter, "cpa.binary",
                            "explicit kij required for every ordered component pair");
            }
        }

        const auto site_exists = [&](const std::string& component_id,
                                     const std::string& site_id) {
            if (!result.components_.contains(component_id)) { return false; }
            const auto index = result.components_.index_of(component_id);
            return std::any_of(result.pure_[index].sites.begin(),
                               result.pure_[index].sites.end(),
                               [&](const CpaAssociationSiteInput& site) {
                                   return site.id == site_id;
                               });
        };

        for (const auto& pair : input.association_pairs) {
            detail::validate_id(pair.first_component_id, "cpa.association.first_component");
            detail::validate_id(pair.second_component_id, "cpa.association.second_component");
            detail::validate_id(pair.first_site_id, "cpa.association.first_site");
            detail::validate_id(pair.second_site_id, "cpa.association.second_site");
            require_cpa(site_exists(pair.first_component_id, pair.first_site_id) &&
                            site_exists(pair.second_component_id, pair.second_site_id),
                        ContractErrorCode::invalid_pair, "cpa.association",
                        "association pair references undeclared site class");
            validate_value(pair.epsilon_j_per_mol, "cpa.association.epsilon_j_per_mol",
                           policy, true);
            validate_value(pair.beta_dimensionless, "cpa.association.beta_dimensionless",
                           policy, false, true);
            const auto key = ordered_association_pair(
                {pair.first_component_id, pair.first_site_id},
                {pair.second_component_id, pair.second_site_id});
            require_cpa(result.association_.emplace(
                            key, CpaAssociationPairParameters{
                                pair.epsilon_j_per_mol.value,
                                pair.beta_dimensionless.value}).second,
                        ContractErrorCode::duplicate_parameter, "cpa.association",
                        "duplicate association site-pair interaction");
        }
        return result;
    }

    [[nodiscard]] std::size_t size() const noexcept { return components_.size(); }
    [[nodiscard]] const OrderedComponents& components() const & noexcept { return components_; }
    const OrderedComponents& components() const && = delete;
    [[nodiscard]] const CpaPureParameters& pure(std::size_t index) const & {
        return pure_.at(index);
    }
    const CpaPureParameters& pure(std::size_t) const && = delete;

    [[nodiscard]] double kij(std::size_t first, std::size_t second) const {
        if (first == second) { return 0.0; }
        const auto key = cpa_detail::ordered_component_pair(
            components_.at(first).id, components_.at(second).id);
        const auto found = kij_.find(key);
        if (found == kij_.end()) {
            throw ContractError(ContractErrorCode::missing_parameter,
                                "cpa.binary", "missing explicit kij");
        }
        return found->second;
    }

    [[nodiscard]] const CpaAssociationPairParameters* association_pair(
        std::size_t first_component, std::string_view first_site,
        std::size_t second_component, std::string_view second_site) const noexcept {
        if (first_component >= components_.size() || second_component >= components_.size()) {
            return nullptr;
        }
        const auto key = cpa_detail::ordered_association_pair(
            {components_.at(first_component).id, std::string(first_site)},
            {components_.at(second_component).id, std::string(second_site)});
        const auto found = association_.find(key);
        return found == association_.end() ? nullptr : &found->second;
    }

    [[nodiscard]] const std::string& dataset_id() const noexcept { return dataset_id_; }
    [[nodiscard]] const std::string& revision() const noexcept { return revision_; }
    [[nodiscard]] const Applicability& applicability() const noexcept { return applicability_; }

private:
    explicit CpaParameterSet(OrderedComponents components)
        : components_(std::move(components)) {}

    OrderedComponents components_;
    std::vector<CpaPureParameters> pure_;
    std::map<std::pair<std::string, std::string>, double> kij_;
    std::map<cpa_detail::AssociationKey, CpaAssociationPairParameters> association_;
    std::string dataset_id_;
    std::string revision_;
    Applicability applicability_;
};

} // namespace mpmc::thermodynamics

#endif // MPMC_THERMODYNAMICS_CPA_PARAMETERS_HPP
