cmake_minimum_required(VERSION 3.21)
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
    project(mpmc_flash LANGUAGES CXX)
endif()
if(NOT TARGET mpmc::thermodynamics)
    add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/../thermodynamics" thermo-library)
endif()
add_library(mpmc_flash INTERFACE)
add_library(mpmc::flash ALIAS mpmc_flash)
target_compile_features(mpmc_flash INTERFACE cxx_std_20)
target_include_directories(mpmc_flash INTERFACE "${CMAKE_CURRENT_SOURCE_DIR}/include")
target_link_libraries(mpmc_flash INTERFACE mpmc::thermodynamics)
