cmake_minimum_required(VERSION 3.21)
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
    project(mpmc_pr76_solver_configuration LANGUAGES CXX)
endif()
if(NOT TARGET mpmc::model_configuration)
    add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/.." model-library)
endif()
if(NOT TARGET mpmc::flash)
    add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/../../flash" flash-library)
endif()
add_library(mpmc_pr76_solver_configuration INTERFACE)
add_library(mpmc::pr76_solver_configuration ALIAS mpmc_pr76_solver_configuration)
target_compile_features(mpmc_pr76_solver_configuration INTERFACE cxx_std_20)
target_link_libraries(mpmc_pr76_solver_configuration INTERFACE mpmc::model_configuration mpmc::flash)
