"""Official writers -> MPMC import/canonical export -> official readers.

Only synthetic linear ASCII fixtures; no MPMC-generated input or golden data.
The .import files expose actual pre-export state, checked against reader data.
"""
import argparse
from datetime import datetime, timezone
import hashlib
import json
import math
from pathlib import Path
import platform
import subprocess
import sys

import gmsh
from vtkmodules.vtkCommonCore import vtkDoubleArray, vtkIdList, vtkPoints, vtkUnsignedLongLongArray
from vtkmodules.vtkCommonDataModel import vtkUnstructuredGrid
from vtkmodules.vtkIOXML import vtkXMLUnstructuredGridWriter

import verify_3d_readers as oracle
import verify_2d_readers as shared
from verify_2d_readers import VerificationError, require, close, vtk_vertex_ids


PATTERNS = {solid[0]: solid[3] for solid in oracle.SOLIDS.values()}
VTK_KIND = {4:10, 5:12, 6:13, 7:14}
GROUPS = {(2,11): ('bottom', {701}), (2,12): ('upper side', {702}),
          (3,21): ('rock & sand', {31,901}), (3,22): ('selected region', {31})}


def fixture(name, disconnected):
    kinds, _, ids, points, cells, _ = oracle.case_data(name)
    points, ids = list(points), list(ids)
    rows = {tag: list(row) for tag, (row, _) in cells.items()}
    interface = (3,4,5) if name == 'tetra_wedge' else (4,5,6,7)
    if disconnected:
        for old in interface:
            rows[31] = [len(points) if v == old else v for v in rows[31]]
            points.append(points[old])
            ids.append(ids[old]+1000)
    return kinds, ids, points, rows, {tag: volume for tag, (_, volume) in cells.items()}


def write_gmsh(path, data):
    kinds, ids, points, rows, _ = data
    gmsh.clear()
    gmsh.model.add('independent-mixed-input')
    for entity in (10,20):
        gmsh.model.addDiscreteEntity(3, entity)
    # Deliberately reverse insertion order and use sparse, nonmonotone tags.
    order = list(reversed(range(len(points))))
    gmsh.model.mesh.addNodes(3, 10, [ids[i] for i in order], [x for i in order for x in points[i]])
    for entity, tag in ((10,901), (20,31)):
        gmsh.model.mesh.addElementsByType(entity, kinds[tag], [tag], [ids[i] for i in rows[tag]])
    # Only two tagged exterior surfaces are explicit. All remaining faces,
    # including the connected interface, must be generated by the importer.
    for entity, tag, row in ((41,701,rows[901][:3 if kinds[901] == 6 else 4]),
                              (42,702,[rows[31][0], rows[31][1], rows[31][-1]])):
        gmsh.model.addDiscreteEntity(2, entity)
        gmsh.model.mesh.addElementsByType(entity, {3:2,4:3}[len(row)], [tag], [ids[i] for i in row])
    for (dim, tag), (label, _) in GROUPS.items():
        entities = {(2,11):[41], (2,12):[42], (3,21):[10,20], (3,22):[20]}[(dim,tag)]
        gmsh.model.addPhysicalGroup(dim, entities, tag, label)
    gmsh.option.setNumber('Mesh.MshFileVersion', 4.1)
    gmsh.option.setNumber('Mesh.Binary', 0)
    gmsh.option.setNumber('Mesh.SaveAll', 1)
    gmsh.write(str(path))
    return {i: tag for i, tag in enumerate(ids)}


def write_vtu(path, data, vtk_kind=VTK_KIND, stable_ids=False):
    kinds, vertex_ids, points, rows, _ = data
    # Rotate/reverse point storage independently of cell connectivity and IDs.
    order = list(reversed(range(len(points))))
    lookup = {old: new for new, old in enumerate(order)}
    grid = vtkUnstructuredGrid()
    vtk_points = vtkPoints()
    vtk_points.SetDataTypeToDouble()
    for i in order:
        vtk_points.InsertNextPoint(points[i])
    grid.SetPoints(vtk_points)
    if stable_ids:
        vertex_identity = vtkUnsignedLongLongArray()
        vertex_identity.SetName('mpmc_global_vertex_id')
        for i in order:
            vertex_identity.InsertNextValue(vertex_ids[i])
        grid.GetPointData().AddArray(vertex_identity)
    identity = vtkUnsignedLongLongArray()
    identity.SetName('mpmc_global_cell_id')
    # Source order 901,31 differs from the usual MPMC Gmsh sort order 31,901.
    for tag in (901,31):
        row = vtkIdList()
        for i in rows[tag]:
            row.InsertNextId(lookup[i])
        grid.InsertNextCell(vtk_kind[kinds[tag]], row)
        identity.InsertNextValue(tag)
    grid.GetCellData().AddArray(identity)
    for target, name, values in (
        (grid.GetPointData(), 'point_marker', [(float(i)+0.25,) for i in order]),
        (grid.GetPointData(), 'position', [points[i] for i in order]),
        (grid.GetCellData(), 'cell_pair', [(90.1,-90.1), (3.1,-3.1)]),
    ):
        array = vtkDoubleArray()
        array.SetName(name)
        array.SetNumberOfComponents(len(values[0]))
        for value in values:
            array.InsertNextTuple(value)
        target.AddArray(array)
    writer = vtkXMLUnstructuredGridWriter()
    errors = []
    writer.AddObserver('ErrorEvent', lambda *_: errors.append('writer error'))
    writer.SetFileName(str(path))
    writer.SetInputData(grid)
    writer.SetDataModeToAscii()
    writer.SetCompressorTypeToNone()
    require(writer.Write() == 1 and not errors and writer.GetErrorCode() == 0, 'official VTK write failed')
    return {old: vertex_ids[old] if stable_ids else new+1 for old, new in lookup.items()}


def read_official(path):
    if path.suffix == '.vtu':
        grid = oracle.read_vtu(path)
        point_ids = vtk_vertex_ids(grid, required=False)
        nodes = {tag: grid.GetPoint(i) for i,tag in enumerate(point_ids)}
        ids = grid.GetCellData().GetArray('mpmc_global_cell_id')
        require(ids is not None and ids.IsA('vtkUnsignedLongLongArray') and
                ids.GetNumberOfComponents() == 1 and ids.GetNumberOfTuples() == grid.GetNumberOfCells(),
                'chain VTU UInt64 cell identity')
        volumes_array = oracle.vtk_volumes(grid)
        cells, volumes, cell_faces = {}, {}, {}
        tags = []
        for i in range(grid.GetNumberOfCells()):
            tag = int(ids.GetValue(i))
            require(tag not in cells, 'duplicate chain VTU cell ID')
            cell = grid.GetCell(i)
            kind = {v:k for k,v in VTK_KIND.items()}.get(grid.GetCellType(i))
            require(kind is not None, 'unsupported chain VTU type')
            cells[tag] = kind, tuple(point_ids[cell.GetPointId(j)] for j in range(cell.GetNumberOfPoints()))
            cell_faces[tag] = []
            for j in range(cell.GetNumberOfFaces()):
                face = cell.GetFace(j)
                cell_faces[tag].append(tuple(point_ids[face.GetPointId(k)] for k in range(face.GetNumberOfPoints())))
            volumes[tag] = float(volumes_array.GetValue(i))
            tags.append(tag)
        fields = {}
        for location, arrays, keys in (('point', grid.GetPointData(), list(nodes)),
                                        ('cell', grid.GetCellData(), tags)):
            for i in range(arrays.GetNumberOfArrays()):
                array = arrays.GetArray(i)
                require(array is not None, 'non-numeric chain field')
                if array.GetName() in ('mpmc_global_cell_id','mpmc_global_vertex_id'):
                    continue
                require(array.GetNumberOfTuples() == len(keys), 'chain field tuple count')
                fields[location, array.GetName()] = {key: array.GetTuple(j) for j,key in enumerate(keys)}
        return dict(nodes=nodes, cells=cells, volumes=volumes, cell_faces=cell_faces,
                    faces={}, groups={}, fields=fields)
    gmsh.clear()
    gmsh.logger.start()
    try:
        gmsh.open(str(path))
        tags, xyz, _ = gmsh.model.mesh.getNodes()
        nodes = {int(tag): tuple(float(x) for x in xyz[3*i:3*i+3]) for i,tag in enumerate(tags)}
        require(len(nodes) == len(tags), 'duplicate chain Gmsh node ID')
        cells = oracle.gmsh_elements(3)
        volumes, cell_faces = {}, {}
        for tag, (kind, row) in cells.items():
            points, weights = gmsh.model.mesh.getIntegrationPoints(kind, 'Gauss2')
            _, determinants, _ = gmsh.model.mesh.getJacobian(tag, points)
            require(len(weights) > 0 and all(d > 0 for d in determinants), 'chain Gmsh Jacobian')
            volumes[tag] = sum(float(w)*float(d) for w,d in zip(weights, determinants, strict=True))
            cell_faces[tag] = [tuple(row[i] for i in face) for face in PATTERNS[kind]]
        faces = {tag: tuple(row) for tag,(_,row) in oracle.gmsh_elements(2).items()}
        groups = {}
        for dim, tag in gmsh.model.getPhysicalGroups():
            dim, tag = int(dim), int(tag)
            members = set()
            for entity in gmsh.model.getEntitiesForPhysicalGroup(dim, tag):
                members.update(oracle.gmsh_elements(dim, int(entity)))
            groups[dim,tag] = gmsh.model.getPhysicalName(dim,tag), members
        require(not any(line.startswith(('Warning:', 'Error:')) for line in gmsh.logger.get()),
                'chain Gmsh reader warning/error')
        require(len(gmsh.view.getTags()) == 0, 'unexpected Gmsh field views')
        return dict(nodes=nodes, cells=cells, volumes=volumes, cell_faces=cell_faces,
                    faces=faces, groups=groups, fields={})
    finally:
        gmsh.logger.stop()


def incidence(snapshot):
    result = {}
    for tag, faces in snapshot['cell_faces'].items():
        require(len({tuple(sorted(face)) for face in faces}) == len(faces), 'duplicate cell faces')
        for face in faces:
            key = tuple(sorted(face))
            require(len(set(face)) == len(face), 'repeated face node')
            result.setdefault(key, set()).add(tag)
    require(all(len(owners) in (1,2) for owners in result.values()), 'nonmanifold chain face')
    return result


def check_geometry(snapshot, name, data, mapping, disconnected):
    kinds, _, points, rows, volumes = data
    require(set(snapshot['nodes']) == set(mapping.values()), 'chain vertex identities/count')
    for i, identity in mapping.items():
        for actual, expected in zip(snapshot['nodes'][identity], points[i], strict=True):
            close(actual, expected, 'chain coordinate m')
    require(set(snapshot['cells']) == set(rows), 'chain cell identities')
    for tag, row in rows.items():
        kind, actual = snapshot['cells'][tag]
        require(kind == kinds[tag] and set(actual) == {mapping[i] for i in row}, 'chain cell type/vertices')
        expected_faces = {tuple(sorted(mapping[row[i]] for i in face)) for face in PATTERNS[kind]}
        require({tuple(sorted(face)) for face in snapshot['cell_faces'][tag]} == expected_faces,
                'chain cell face connectivity')
        close(snapshot['volumes'][tag], volumes[tag], 'chain analytic cell volume m^3')
    close(sum(snapshot['volumes'].values()), sum(volumes.values()), 'chain total volume m^3')
    faces = incidence(snapshot)
    internal = sum(len(owners) == 2 for owners in faces.values())
    triangle = name == 'tetra_wedge'
    require(internal == (0 if disconnected else 1), 'chain shared-face incidence')
    require(len(faces) == (9 if triangle else 11)-(0 if disconnected else 1), 'chain unique face count')
    interface_result = None
    if not disconnected:
        interface = (3,4,5) if triangle else (4,5,6,7)
        interface_result = oracle.check_incidence(
            name, snapshot['nodes'], {tag:row for tag,(_,row) in snapshot['cells'].items()},
            snapshot['cell_faces'], [mapping[i] for i in interface])
    return {'unique_faces': len(faces), 'interior_faces': internal,
            'boundary_faces': len(faces)-internal, 'volumes_m3': snapshot['volumes'],
            'shared_face': interface_result}


def check_fields(snapshot, data, mapping, present):
    _, _, points, _, _ = data
    expected = {('point','point_marker'): {mapping[i]:(float(i)+0.25,) for i in mapping},
                ('point','position'): {mapping[i]:point for i,point in enumerate(points)},
                ('cell','cell_pair'): {31:(3.1,-3.1), 901:(90.1,-90.1)}} if present else {}
    require(set(snapshot['fields']) == set(expected), 'chain field names/locations')
    for key, values in expected.items():
        require(set(snapshot['fields'][key]) == set(values), 'chain field entity binding')
        for identity, value in values.items():
            actual = snapshot['fields'][key][identity]
            require(len(actual) == len(value), 'chain field component count')
            for a,b in zip(actual,value,strict=True):
                close(a,b,'chain field value')


def read_import(path):
    snapshot = dict(nodes={}, cells={}, volumes={}, cell_faces={}, faces={}, groups={}, fields={})
    face_details, cell_face_ids = {}, {}
    for line in path.read_text(encoding='utf-8').splitlines():
        words = line.split()
        kind, tag = map(int, words[:2])
        target = snapshot[{0:'nodes',3:'cells',2:'faces'}[kind]]
        require(tag not in target, 'duplicate imported entity identity')
        if kind == 0:
            require(len(words) == 5, 'imported vertex record shape')
            target[tag] = tuple(map(float,words[2:]))
            continue
        width = int(words[2])
        row = tuple(map(int,words[3:3+width]))
        tail = words[3+width:]
        if kind == 3:
            target[tag] = {4:4,8:5,6:6,5:7}[width], row
            snapshot['volumes'][tag] = float(tail[0])
            count = int(tail[1])
            require(len(tail) == 2+count, 'imported cell record shape')
            cell_face_ids[tag] = tuple(map(int,tail[2:]))
        else:
            target[tag] = row
            count = int(tail[0])
            require(len(tail) == 8+count, 'imported face record shape')
            face_details[tag] = dict(owners=set(map(int,tail[1:1+count])), boundary=int(tail[1+count]),
                physical=int(tail[2+count]), area=float(tail[3+count]), owner=int(tail[4+count]),
                normal=tuple(map(float,tail[5+count:])))
    for tag, ids in cell_face_ids.items():
        snapshot['cell_faces'][tag] = [snapshot['faces'][i] for i in ids]
    faces = incidence(snapshot)
    require(len(faces) == len(snapshot['faces']), 'imported duplicate/orphan faces')
    for tag, row in snapshot['faces'].items():
        detail = face_details[tag]
        owners = faces[tuple(sorted(row))]
        require(detail['owners'] == owners, 'imported cell-face / face-cell reciprocity')
        require(detail['boundary'] == int(len(owners) == 1), 'imported boundary classification')
        require(detail['owner'] in owners, 'imported geometry owner')
        vertices = [snapshot['nodes'][v] for v in row]
        vector = [oracle.cross(oracle.subtract(vertices[i],vertices[0]),
                               oracle.subtract(vertices[i+1],vertices[0])) for i in range(1,len(row)-1)]
        vector = tuple(sum(v[i] for v in vector)/2 for i in range(3))
        area = math.sqrt(oracle.dot(vector,vector))
        close(detail['area'],area,'imported face area m^2')
        cell = [snapshot['nodes'][v] for v in snapshot['cells'][detail['owner']][1]]
        sign = 1 if oracle.dot(vector,oracle.subtract(oracle.mean(vertices),oracle.mean(cell))) > 0 else -1
        for a,b in zip(detail['normal'],[sign*v/area for v in vector],strict=True):
            close(a,b,'imported owner outward normal')
    return snapshot, face_details


def check_report(path, codes):
    lines = path.read_text(encoding='utf-8').splitlines()
    require(lines and lines[0] == ('lossy' if codes else 'lossless') and
            len(lines[1:]) == len(codes) and set(lines[1:]) == codes, f'chain loss report: {path.name}: {lines}')


def run_case(directory, producer, name, source, disconnected):
    data = fixture(name, disconnected)
    suffix = '.msh' if source == 'gmsh' else '.vtu'
    stem = name+'_'+source+('_disconnected' if disconnected else '')
    path = directory/(stem+'_input'+suffix)
    mapping = (write_gmsh if source == 'gmsh' else write_vtu)(path,data)
    original = read_official(path)
    check_geometry(original,name,data,mapping,disconnected)
    check_fields(original,data,mapping,source == 'vtu')
    require(original['groups'] == (GROUPS if source == 'gmsh' else {}), 'official input physical groups')
    if source == 'gmsh':
        require(set(original['faces']) == {701,702}, 'official input must omit generated faces')
    run = subprocess.run([str(producer),'--convert-3d',source,path.name,stem], cwd=directory,
                         capture_output=True,text=True,timeout=60)
    require(run.returncode == 0, f'MPMC conversion failed: {run.stdout}\n{run.stderr}')
    imported, details = read_import(directory/(stem+'.import'))
    imported_result = check_geometry(imported,name,data,mapping,disconnected)
    require(all(detail['physical'] == ({701:11,702:12}.get(tag,0) if source == 'gmsh' else 0)
                for tag,detail in details.items()), 'imported boundary physical tags')
    for tag,row in original['faces'].items():
        require(tag in imported['faces'] and set(row) == set(imported['faces'][tag]), 'imported explicit face IDs')
    results = {}
    for target in ('gmsh','vtu'):
        output = directory/(stem+('.msh' if target == 'gmsh' else '.vtu'))
        actual = read_official(output)
        lookup = {tag:i+1 for i,tag in enumerate(imported['nodes'])}
        target_mapping = mapping
        if target == 'vtu':
            vtk_vertex_ids(oracle.read_vtu(output))
        results[target] = check_geometry(actual,name,data,target_mapping,disconnected)
        check_fields(actual,data,target_mapping,source == target == 'vtu')
        require(actual['groups'] == (GROUPS if source == target == 'gmsh' else {}), 'output physical groups')
        if target == 'gmsh':
            require(set(actual['faces']) == set(imported['faces']), 'exported imported/generated face identities')
            for tag,row in imported['faces'].items():
                require(set(actual['faces'][tag]) == set(row), 'exported face identity binding')
        codes = set()
        if source == 'gmsh' and target == 'vtu':
            codes = {'vtu.groups_not_serialized','vtu.face_tags_not_serialized',
                     'vtu.face_ids_remapped'}
        if source == 'vtu' and target == 'gmsh':
            codes = {'gmsh.fields_not_serialized'}
        if target == 'vtu':
            # Compare stable point identity and regenerated face bindings.
            vertex_loss = set(actual['nodes']) != set(imported['nodes'])
            keys = sorted((tuple(sorted(lookup[v] for v in key)) for key in incidence(actual)),
                          key=lambda key:(len(key),key))
            reimported_faces = {key:i+1 for i,key in enumerate(keys)}
            face_loss = any(tag != reimported_faces[tuple(sorted(lookup[v] for v in row))]
                            for tag,row in imported['faces'].items())
            require(not vertex_loss, 'actual VTU vertex identities changed')
            require(face_loss == ('vtu.face_ids_remapped' in codes), 'actual VTU face ID loss differs')
            results[target]['identity_losses'] = {'vertices':vertex_loss,'faces':face_loss}
        check_report(Path(str(output)+'.report'),codes)
        if disconnected:
            try:
                check_geometry(actual,name,data,target_mapping,False)
            except VerificationError as error:
                require(str(error) == 'chain shared-face incidence', 'control failed for unrelated reason')
                results[target]['connected_contract_rejection'] = str(error)
            else:
                raise VerificationError('disconnected input was silently welded')
    print(f'[PASS] independent.3d.chain.{stem}')
    return {'input':path.name, 'imported':imported_result, 'outputs':results, 'converter_stdout':run.stdout}


def run_vertex_identity_case(directory, producer, name, dimension, data, read, imported_read, geometry):
    kinds, ids, points, rows, measures = data
    ids = list(ids)
    ids[:3] = [0,2**64-1,2**53+1]
    data = kinds, ids, points, rows, measures
    stem = name+'_vertex_ids'
    path = directory/(stem+'_input.vtu')
    mapping = write_vtu(path,data,{2:5,3:9} if dimension == 2 else VTK_KIND,stable_ids=True)
    disconnected = name.endswith('_disconnected')
    fixture_name = name.removesuffix('_disconnected')
    original = read(path)
    geometry(original,fixture_name,data,mapping,disconnected)
    check_fields(original,data,mapping,True)
    run = subprocess.run([str(producer),f'--convert-{dimension}d','vtu',path.name,stem],cwd=directory,
                         capture_output=True,text=True,timeout=60)
    require(run.returncode == 0, f'vertex identity conversion failed: {run.stdout} {run.stderr}')
    imported, _ = imported_read(directory/(stem+'.import'))
    before = geometry(imported,fixture_name,data,mapping,disconnected)
    output = directory/(stem+'.vtu')
    actual = read(output)
    vtk_vertex_ids(oracle.read_vtu(output))
    after = geometry(actual,fixture_name,data,mapping,disconnected)
    check_fields(actual,data,mapping,True)
    check_report(Path(str(output)+'.report'),set())
    print(f'[PASS] independent.{dimension}d.vertex_ids.{name}')
    return dict(input=path.name,imported=before,output=after,vertex_ids=ids,
                converter_stdout=run.stdout)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--producer',type=Path,required=True)
    parser.add_argument('--output-dir',type=Path,required=True)
    args = parser.parse_args()
    directory = args.output_dir.resolve()
    directory.mkdir(parents=True,exist_ok=False)
    producer = args.producer.resolve(strict=True)
    report = dict(status='failed',started_utc=datetime.now(timezone.utc).isoformat(),
                  platform=platform.platform(),python=sys.version,gmsh=gmsh.__version__,
                  vtk=oracle.vtkVersion.GetVTKVersion(),
                  producer_sha256=hashlib.sha256(producer.read_bytes()).hexdigest(),
                  scripts_sha256={Path(p).name:hashlib.sha256(Path(p).read_bytes()).hexdigest()
                                  for p in (__file__,oracle.__file__,shared.__file__)},cases={})
    gmsh.initialize(['mpmc-independent-chain-3d'],readConfigFiles=False)
    gmsh.option.setNumber('General.Terminal',0)
    try:
        for name in ('tetra_wedge','hexa_pyramid'):
            for source in ('gmsh','vtu'):
                for disconnected in (False,True):
                    key=name+'_'+source+('_disconnected' if disconnected else '')
                    report['cases'][key]=run_case(directory,producer,name,source,disconnected)
        report['vertex_identity_cases'] = {
            name+('_disconnected' if disconnected else ''): run_vertex_identity_case(
                directory,producer,name+('_disconnected' if disconnected else ''),3,fixture(name,disconnected),
                read_official,read_import,check_geometry)
            for name in ('tetra_wedge','hexa_pyramid') for disconnected in (False,True)}
        report['vertex_identity_inputs'] = len(report['vertex_identity_cases'])
        report.update(status='passed',inputs=4,chains=8,conversion_reports=8,
                      disconnected_inputs=4,disconnected_chains=8,disconnected_reports=8,import_snapshots=8)
        print('[PASS] independent.mesh.3d_chains inputs=4 chains=8 reports=8 disconnected_chains=8')
    except Exception as error:
        report['error']=str(error)
        print(f'[FAIL] {error}',file=sys.stderr)
        return 1
    finally:
        gmsh.finalize()
        report['output_sha256']={p.relative_to(directory).as_posix():hashlib.sha256(p.read_bytes()).hexdigest()
                                 for p in sorted(directory.rglob('*')) if p.is_file()}
        (directory/'result.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
