cmake_minimum_required(VERSION 3.21)
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
    project(mpmc_physics LANGUAGES CXX)
endif()
if(NOT TARGET mpmc::flash_sensitivity)
    add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/../flash/sensitivity" flash-sensitivity-library)
endif()
add_library(mpmc_physics INTERFACE)
add_library(mpmc::physics ALIAS mpmc_physics)
target_compile_features(mpmc_physics INTERFACE cxx_std_20)
target_include_directories(mpmc_physics INTERFACE "${CMAKE_CURRENT_SOURCE_DIR}/include")
target_link_libraries(mpmc_physics INTERFACE mpmc::flash_sensitivity)
